let shopItemsData = [
  {
    id: "jfhgbv234nscs",
    name: "cleaning kits",
    price: 45,
    desc: "123",
    img: "marketImages/bathbomb.webp",
  },
  {
    id: "ioytrh234ndcv",
    name: "cutlery",
    price: 20,
    desc: "123",
    img: "marketImages/cutlery.avif",
  },
  {
    id: "wuefbnc234xbsn",
    name: "plate",
    price: 25,
    desc: "123",
    img: "marketImages/plate.avif",
  },
  {
    id: "thyfh234cbcv",
    name: "puff",
    price: 30,
    desc: "123",
    img: "marketImages/puff.avif",
  },
  {
    id: "thiecbaw234dj234ksadjk",
    name: "bamboo straw",
    price: 15,
    desc: "123",
    img: "marketImages/straw.jpeg",
  },
  {
    id: "iuert234ryw234ebncdjksadjk",
    name: "shampoo bar",
    price: 19,
    desc: "123",
    img: "marketImages/soap.avif",
  },
  {
    id: "thiery234234234tbvcbvzdhadjk",
    name: "bath bomb",
    price: 42,
    desc: "123",
    img: "marketImages/shampoo.webp",
  },
  {
    id: "trfoiwfcs234dfsdfnbcawdjksadjk",
    name: "coconut bowl",
    price: 42,
    desc: "123",
    img: "marketImages/coconu.jpeg",
  },
  {
    id: "cbvxbcsdfsd234fvsceldk",
    name: "banana leaf plate",
    price: 85,
    desc: "123",
    img: "marketImages/leafplate.jpeg",
  },
  {
    id: "oiopijsdfsvm234jkhuihb",
    name: "paper togo box",
    price: 11,
    desc: "123",
    img: "marketImages/leaftogobox.jpeg",
  },
  {
    id: "asdassdfsdfd234sfdasd",
    name: "paper bag",
    price: 35,
    desc: "123",
    img: "marketImages/zzzzz.jpg",
  },
  {
    id: "rtytytsdfsfuyu234ytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytytsdfsdfuyuy234tyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytytsfd234sdfuyuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytytu234sdfsdfyuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtyty234tuysfsfuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytytuyuy234tysdfsfytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytytuyu234ytyytsdfsdfbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytytuyu234ytyysdfsdftbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytsfs234dfytuyuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytysfsftu234yuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytytuysf234sfdfuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytytsdfd234sfuyuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytytsdfsd234fuyuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytysdfsftu234yuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytys234dfsfdtuyuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtyt123ytusdfsdfyuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
  {
    id: "rtytytuyuysfsdftyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "marketImages/taco.jpeg",
  },
];
