let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "cleaning kits",
    price: 45,
    desc: "123",
    img: "/img/marketImages/bathbomb.webp",
  },
  {
    id: "ioytrhndcv",
    name: "oakwood cutlery",
    price: 20,
    desc: "123",
    img: "/img/marketImages/cutlery.avif",
  },
  {
    id: "wuefbncxbsn",
    name: "plate",
    price: 25,
    desc: "123",
    img: "/img/marketImages/plate.avif",
  },
  {
    id: "thyfhcbcv",
    name: "puff",
    price: 30,
    desc: "123",
    img: "/img/marketImages/puff.avif",
  },
  {
    id: "thiecbawdjksadjk",
    name: "bamboo straw",
    price: 15,
    desc: "123",
    img: "/img/marketImages/straw.jpeg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "shampoo bar",
    price: 19,
    desc: "123",
    img: "/img/marketImages/soap.avif",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "bath bomb",
    price: 42,
    desc: "123",
    img: "/img/marketImages/shampoo.webp",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "coconut bowl",
    price: 42,
    desc: "123",
    img: "/img/marketImages/coconu.jpeg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "banana leaf plate",
    price: 85,
    desc: "123",
    img: "/img/marketImages/leafplate.jpeg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "paper togo box",
    price: 11,
    desc: "123",
    img: "/img/marketImages/leaftogobox.jpeg",
  },
  {
    id: "asdasdasd",
    name: "paper bag",
    price: 35,
    desc: "123",
    img: "/img/marketImages/zzzzz.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "nachos",
    price: 12,
    desc: "123",
    img: "/img/marketImages/taco.jpeg",
  },
];
